web:
  upload_path: /home/IKDData/upload #无状态信息存储路径，在centos中则需要调整

debug: false
server:
  port: 8082

spring:
  cloud:
    consul:
      host: 192.168.2.42
      port: 8500
      discovery:
        register: true
        hostname: 192.168.2.42
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: urlprefix-/${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

feign:
  hystrix:
    enabled: true

#高版本的时间控制有两个地方ribbon，hystrix 先ribbon 后hystrix
#请求处理的超时时间,超时则进行熔断降级处理
ribbon:
  ReadTimeout: 3000000
  #请求连接的超时时间
  ConnectTimeout: 3000000


#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 40000
