#debug配置是否调试模式，如果打包发布的话，需要设置为false。
#默认情况下，spring boot从控制台打印出来的日志级别有error，warn，info，如果你要打印debug级别的日志，可设置debug=true
debug: false
#server.port配置的是 Spring Boot 服务的端口
server:
  port: 8081
  servlet:
    session:
      timeout: 86400 #单位为s
#算法接口
serverIP: http://192.168.68.88:5555
try_time: 1


spring:
  cloud:
    consul:
      host: 192.168.68.86
      port: 8500
      discovery:
        register: true
        hostname: 192.168.68.86
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: urlprefix-/${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  #静态化和外部文件存放配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:  classpath:/META-INF/resources,classpath:/resources/,classpath:/static/,classpath:/public/, file:${web.upload_path}

  #mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.68.89:3306/yk_ai?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  aop:
    proxy-target-class: true
    auto: true

#c3p0配置
c3p0:
  driverClass: ${spring.datasource.driver-class-name}
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  maxPoolSize: 30
  minPoolSize: 10
  autoCommitOnClose: false
  checkoutTimeout: 120000
  acquireIncrement: 2
  testConnectionOnCheckin: false
  testConnectionOnCheckout: true
  initialPoolSize: 10
  maxIdleTime: 300
  idleConnectionTestPeriod: 60

#文件路径
filePath:
  attachment: \\192.168.2.66\\yrFile\\attachment\\
  mapFilePath: \\192.168.2.66\\yrFile\\mapfile\\
  aoiMergePath: \\192.168.2.66\\yrFile\\aoi\\
  fenxuanPath: \\192.168.2.66\\yrFile\\fenxuan\\
  sortingPath: \\192.168.2.66\\yrFile\\分选母片文档\\
  binSourcePath: \\192.168.2.66\\yrFile\\binOutputfiles\\
  binTargetPath: \\192.168.2.66\\yrFile\\Chip\\

#特定用户查询
role:
  alnRole: 1539a61545a14fd1985c1498c774fa3a
  beakRole: 48bbe604d16d438fa681c84780072834

site:
  cotSiteId: 28
  residualSiteId: 29

process:
  cotProcessId: 73
