#debug配置是否调试模式，如果打包发布的话，需要设置为false。
debug: true
#server.port配置的是 Spring Boot 服务的端口
server:
  port: 8081

#算法接口
serverIP: http://192.168.2.39:5000
try_time: 1


spring:
  cloud:
    consul:
      host: 192.168.2.42
      port: 8500
      discovery:
        register: true
        hostname: 192.168.2.42
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: urlprefix-/${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  #静态化和外部文件存放配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:  classpath:/META-INF/resources,classpath:/resources/,classpath:/static/,classpath:/public/, file:${web.upload_path}

  #mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.42:3306/quanshisoft?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: Traits1023~
    type: com.mchange.v2.c3p0.ComboPooledDataSource

#c3p0配置
c3p0:
  driverClass: ${spring.datasource.driver-class-name}
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  maxPoolSize: 30
  minPoolSize: 10
  autoCommitOnClose: false
  checkoutTimeout: 1000
  acquireIncrement: 2
  testConnectionOnCheckin: false
  testConnectionOnCheckout: true
  initialPoolSize: 10
  maxIdleTime: 300
  idleConnectionTestPeriod: 60
