debug: true
server:
  port: 90

spring:
  cloud:
    consul:
      host: 192.168.18.47
      port: 8500
      discovery:
        register: true
        hostname: 192.168.18.47
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: urlprefix-/${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#通过网关避免跨域问题
zuul:
  ignored-services: "*"
  sensitive-headers:
  routes:
    api:  # 该配置方式中，hello1只是给路由一个名称，可以任意起名。
      path: /api/**
      service-id: zuulgate-service  # service-id对应服务在注册中心的名称
      sensitiveHeaders: "*"
    hiveservice:
      path: /hiveservice/**
      serviceId: hive-service #hive服务
      sensitiveHeaders: "*"
    mysqldataservice:
      path: /mysqldataservice/**
      serviceId: mysqldata-service #mysqldata服务
      sensitiveHeaders: "*"
    webviewserver:
      path: /webviewserver/**
      serviceId: webview-server #web展示服务
      sensitiveHeaders: "*"
    flowservice:
      path: /flowservice/**
      serviceId: flow-service   #流程服务
      sensitiveHeaders: "*"
    htmlserver:
      path: /htmlserver/**
      url: http://www.wiseq.cn #静态页面

    jsonserver:
      path: /json/**
      url: http://192.168.2.54:8082/swagger-ui.html
  host:
    connect-timeout-millis: 300000
    socket-timeout-millis: 300000
  servlet-path: /

# 如果不配置重试，默认会重试一次
ribbon:
  ReadTimeout: 60000 #1min
  ConnectTimeout: 60000 #1min
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试 false只针对get请求

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
#http://192.168.2.57/webviewserver/user/1/detail


# 授权配置
license:
  subject: AiEngineForMLS
  #别名
  publicAlias: publicCert
  #公钥密码
  storePass: Traits1023~
  # 授权文件
  licensePath: /home/license/license.lic
  # 公钥地址
  publicKeysStorePath: /home/license/publicCerts.keystore